apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go-web-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "go-web-app.fullname" . }}
                port:
                  number: 80
